### ISSUE TITLE
Some elements are not translated when using Firefox

### ISSUE THREAD

**Issue by bpross-52n** [52North/wps-js-client#2]
In the dropbox for choosing a WPS after switching to English it still says "WPS wählen" instead of "select WPS" (see screenshot). Seems to be working in Chrome.

![wps-js-client-issue](https://cloud.githubusercontent.com/assets/3692794/17883818/101f5d8a-6915-11e6-804e-1ded2eb1a803.png)

**Comment by cDanowski** [comment]
okay, the funny thing ist, when I do it and then alter zoom level in Firefox, the text value is replaced properly...
Currently I am unable to fix this issue. But I will keep searching

**Comment by cDanowski** [comment]
the complete page is kind of unusable in firefox... asynchrounously incoming messages are not updateing the view properly. I have to take a deeper look.
Using Chrome, Edge, everything works

**Comment by cDanowski** [comment]
at least the  support for firefox is now implemented (had some namespace issues, trying to correctly select XML nodes with namespaces using JQuery.)

**Comment by cDanowski** [comment]
now fixed by #4 

the problem was the attribute "hidden" on select elements. This prevented firefox to display the updated placeholder value. Now, all occurrences of "hidden" are replaced by "disabled".
